/*
아이디 새로 만들기
sqlplus sys/oracle as sysdba

create user local_dev
identified by autoever
account unlock;

grant connect, resource to local_dev;

alter user local_dev quota unlimited on users;
*/

--유저정보(로그인)
CREATE TABLE USERIFTB(
  USER_ID VARCHAR2(12) PRIMARY KEY, 
  USER_PWD VARCHAR2(20) NOT NULL
  );
  
COMMENT ON TABLE USERIFTB IS '유저정보';
COMMENT ON COLUMN USERIFTB.USER_ID IS '아이디';
COMMENT ON COLUMN USERIFTB.USER_PWD IS '패스워드';

--자동차
CREATE TABLE CARINFTB(
  CAR_NO NUMBER PRIMARY KEY,
  CAR_SIZE VARCHAR2(8) NOT NULL,
  CAR_TYPE VARCHAR2(20) NOT NULL,
  MILEAGE NUMBER NOT NULL,
  BIRTH DATE NOT NULL,
  CAPACITY NUMBER NOT NULL,
  COST NUMBER NOT NULL,
  LATITUDE FLOAT,
  LONGITUDE FLOAT
  );
  
COMMENT ON TABLE CARINFTB IS '차정보';
COMMENT ON COLUMN CARINFTB.CAR_NO IS '식별번호';
COMMENT ON COLUMN CARINFTB.CAR_SIZE IS '차종';
COMMENT ON COLUMN CARINFTB.CAR_TYPE IS '차이름';
COMMENT ON COLUMN CARINFTB.MILEAGE IS '주행거리';
COMMENT ON COLUMN CARINFTB.BIRTH IS '연식';
COMMENT ON COLUMN CARINFTB.CAPACITY IS '인승';
COMMENT ON COLUMN CARINFTB.COST IS '비용/km';
COMMENT ON COLUMN CARINFTB.LATITUDE IS '위도';
COMMENT ON COLUMN CARINFTB.LONGITUDE IS '경도';

--대여
CREATE TABLE CARRENTB(
  RENT_NO NUMBER PRIMARY KEY,
  CAR_NO NUMBER NOT NULL,
  USER_ID VARCHAR2(12) NOT NULL,
  RENT_DATE DATE NOT NULL,
  RETURN_DATE DATE
  );

COMMENT ON TABLE CARRENTB IS '대여정보';
COMMENT ON COLUMN CARRENTB.RENT_NO IS '대여번호';
COMMENT ON COLUMN CARRENTB.CAR_NO IS '식별번호';
COMMENT ON COLUMN CARRENTB.USER_ID IS '아이디';
COMMENT ON COLUMN CARRENTB.RENT_DATE IS '대여날짜';
COMMENT ON COLUMN CARRENTB.RETURN_DATE IS '반납날짜';

--시동
CREATE TABLE ACTIVATB(
  CAR_NO NUMBER PRIMARY KEY,
  START_YN VARCHAR2(1) NOT NULL
  );

COMMENT ON TABLE ACTIVATB IS '시동정보';
COMMENT ON COLUMN ACTIVATB.CAR_NO IS '식별번호';
COMMENT ON COLUMN ACTIVATB.START_YN IS '시동여부';

--시동로그
CREATE TABLE ACTLOGTB(
  START_NO NUMBER PRIMARY KEY,
  CAR_NO NUMBER NOT NULL,
  ON_DATE DATE NOT NULL,
  OFF_DATE DATE
  );

COMMENT ON TABLE ACTLOGTB IS '시동Log';
COMMENT ON COLUMN ACTLOGTB.START_NO IS '시동번호';
COMMENT ON COLUMN ACTLOGTB.CAR_NO IS '식별번호';
COMMENT ON COLUMN ACTLOGTB.ON_DATE IS '시동ON날짜';
COMMENT ON COLUMN ACTLOGTB.OFF_DATE IS '시동OFF날짜';

--주행정보
CREATE TABLE DRVINFTB(
  RENT_NO NUMBER NOT NULL,
  LATITUDE FLOAT NOT NULL,
  LONGITUDE FLOAT NOT NULL,
  TIMESTAMP DATE NOT NULL
  );

COMMENT ON TABLE DRVINFTB IS '주행정보';
COMMENT ON COLUMN DRVINFTB.RENT_NO IS '대여번호';
COMMENT ON COLUMN DRVINFTB.LATITUDE IS '위도';
COMMENT ON COLUMN DRVINFTB.LONGITUDE IS '경도';
COMMENT ON COLUMN DRVINFTB.TIMESTAMP IS '시간';